width: 960             #图像宽度 1440 1280 960 640
height: 720            #图像高度 1080 960 720 480
Offset_x: 324             #X方向偏置
Offset_y: 272             #Y方向偏置
# width: 640             #图像宽度 1440 1280 960 640
# height: 480            #图像高度 1080 960 720 480
# Offset_x: 460             #X方向偏置
# Offset_y: 408             #Y方向偏置


PixelFormat: 12         #像素格式，12: BayerRG8

FrameRateEnable: true   #使能 
FrameRate: 100           #帧率

ExposureTime: 2000      #曝光时间
ExposureAuto: false
AutoExposureTimeLowerLimit: 100
AutoExposureTimeUpperLimit: 16777

BalanceWhiteAuto: 1

Brightness: 100

GammaEnable: true
GammaSelector: 1        #1: User
Gamma: 0.7              #伽马因子

GainAuto: 2             #亮度的固定增益

CalibrateEnable: true

ResizeEnable: false
DestinationHeight: 640
DestinationWidth: 640

# ImageCompressionMode: 1
# ImageCompressionQuality: 50

TriggerMode: 0

# hikrobot_camera:
#   rgb:
#     compressed:
#       format: "png"
#       png_level: 100